### ISSUE TITLE
Please take arrow color into consideration for the bar shown at 0 also.

### ISSUE THREAD

**Issue by georgepauna** [JonahKr/power-distribution-card#128]
I'm setting arrows to transparent if power is less than some threshold and it works for small values, but for 0, the bar appears instead.

**Comment by Lateadapter** [comment]
@georgepauna 
What possibly might work for you is setting the arrow color to: "var(--card-background-color)"
As a result arrows and bar are still there but not visible at all.

**Comment by georgepauna** [comment]
@Lateadapter thank for taking interest, but it doesn't work. I think color is ignored for the bar that appears at value 0. Using your suggestion, it's 100% the same as using transparent (i.e. bar still visible at 0, grey)

**Comment by Lateadapter** [comment]
@georgepauna 
Indeed you are right! I'm using that method for a sensor never reaching exactly "0". Now I played a bit around and can confirm your findings.

**Comment by JonahKr** [comment]
Fixed in the latest release. Take care! 👍

**Comment by georgepauna** [comment]
> Fixed in the latest release. Take care! 👍

Thanks for looking into it, but it's still not working in 2.5.8 :)

**Comment by JonahKr** [comment]
yep i borked the value calc... will release a hotfix in a sec

**Comment by georgepauna** [comment]
Yes, I saw even arrow directions were wrong. All good with 2.5.9, thanks a lot!
